version: "3.8"

services:

    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
            - .docker/php/php.ini:/usr/local/etc/php/php.ini
            - .docker/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
            # - .docker/php/entrypoint.sh:/usr/local/bin/entrypoint.sh
            - .docker/php/.bashrc:/root/.bashrc

    nginx:
        image: nginx
        ports:
            - 7070:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            
    db:
        image: postgres:16
        ports:
            - 5002:5432
        volumes:
            - .docker/db/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379

    # mail:
    #     image: axllent/mailpit:latest
    #     ports:
    #     - 8025:8025
    #     - 1025:1025
